### ISSUE TITLE
数据库查找相关的性能问题

### ISSUE THREAD

**Issue by ouuan** [ouuan/Hinata-Online-Judge#4]
https://github.com/ouuan/Hinata-Online-Judge/blob/master/web/app/controllers/problem_set.php 中有大量数据库查询，不清楚 MySQL 底层实现，也不知道评测记录多了会不会有明显的性能问题..

感觉可以通过在数据库里存每道题每个人的最高得分以及 AC 人数、提交人数解决。

**Comment by ouuan** [comment]
先咕着，MySQL 水平更高（~~哪天评测记录真的多到暴力数据库会 T~~）的时候再说吧。

**Comment by Menci** [comment]
![image](https://user-images.githubusercontent.com/11341955/80593898-96328280-8a54-11ea-862f-b1e80cfd36b2.png)

这是什么操作？

**Comment by ouuan** [comment]
> 这是什么操作？

看起来是更新某人某题分数最大的提交..都是半年前写的东西了，现在 MySQL 都忘得差不多了。当时也是全靠 Google，没系统地学习 MySQL。

**Comment by Menci** [comment]
令人智熄的操作 … 为什么不用分组聚合 …
